----------------TYPES----------------

CREATE TYPE CALL_TYPE AS ENUM(
	'VOICE', 'VIDEO'
);

CREATE TYPE PARTICIPANT_ROLE AS ENUM(
	'HOST',
 	'PARTICIPANT'
);

CREATE TYPE CALL_ENDED_REASON AS ENUM(
	'USER_HANGUP', 'TIMEOUT', 'ERROR', 'CALL_ENDED_NORMALLY'
); 


CREATE TYPE ENCRYPTION_TYPE AS ENUM(
	'NONE',
    'DTLS',
    'SRTP',
    'END_TO_END'
);


CREATE TYPE CONVERSATION_TYPE AS ENUM (
    'DIRECT',   -- 1-to-1
    'GROUP'     -- multi-user
);


CREATE TYPE CHAT_TYPE AS ENUM(
	'TEXT', 
	'VIDEO', 
	'PICTURE',
	'AUDIO', 
	'DRAW'
);


----------------LOOKUP TABLES---------------- 

CREATE TABLE ALGORITHM_TYPE(
	ALGORITHM_TYPE_ID SMALLINT,
	ALGORITHM_NAME VARCHAR(64),
	ALGORITHM_DESCRIPTION TEXT,
	
	CONSTRAINT ALGORITHM_TYPE_PK
		PRIMARY KEY (ALGORITHM_TYPE_ID),
	
	CONSTRAINT ALGORITHM_NAME_UK
		UNIQUE (ALGORITHM_NAME),

	CONSTRAINT ALGORITHM_NAME_CHECK
		CHECK(ALGORITHM_NAME IS NOT NULL)
);


CREATE TABLE CLIENT_STATUS(
	CLIENT_STATUS_ID SMALLINT,
	CLIENT_STATUS_NAME VARCHAR(64),

	CONSTRAINT CLIENT_STATUS_ID_PK
		PRIMARY KEY (CLIENT_STATUS_ID),

	CONSTRAINT CLIENT_STATUS_NAME_UK
		UNIQUE (CLIENT_STATUS_NAME),

	CONSTRAINT CLIENT_STATUS_NAME_CHECK
		CHECK(CLIENT_STATUS_NAME IS NOT NULL)
);


CREATE TABLE DEVICE_TYPE(
	DEVICE_TYPE_ID SMALLINT,
	DEVICE_TYPE_NAME VARCHAR(64),

	CONSTRAINT DEVICE_TYPE_PK
		PRIMARY KEY (DEVICE_TYPE_ID),

	CONSTRAINT DEVICE_TYPE_NAME_UK
		UNIQUE (DEVICE_TYPE_NAME),

	CONSTRAINT DEVICE_TYPE_NAME_CHECK
		CHECK(DEVICE_TYPE_NAME IS NOT NULL)
);

CREATE TABLE REQUEST_RESULT(
	REQUEST_RESULT_ID SMALLINT, 
	RESULT VARCHAR(64),

	CONSTRAINT REQUEST_RESULT_PK
		PRIMARY KEY (REQUEST_RESULT_ID),
	
	CONSTRAINT REQUEST_RESULT_UK
		UNIQUE(RESULT),
	
	CONSTRAINT REQUEST_RESULT_CHECK
		CHECK(RESULT IS NOT NULL)
);


CREATE TABLE ACTION_TYPE(
	ACTION_TYPE_ID SMALLINT,
	ACTION_NAME VARCHAR(64),

	CONSTRAINT ACTION_TYPE_PK
		PRIMARY KEY (ACTION_TYPE_ID),

	CONSTRAINT ACTION_TYPE_NAME_UK
		UNIQUE(ACTION_NAME),

	CONSTRAINT ACTION_TYPE_NAME_CHECK
		CHECK(ACTION_NAME IS NOT NULL)
);


CREATE TABLE REQUEST_TYPE(
	REQUEST_TYPE_ID SMALLINT,
	REQUEST_TYPE_NAME VARCHAR(64) NOT NULL,
	REQUEST_METHOD VARCHAR(64),
	
	CONSTRAINT REQUEST_TYPE_PK
		PRIMARY KEY(REQUEST_TYPE_ID),

	CONSTRAINT REQUEST_TYPE_NAME_METHOD_UK
		UNIQUE(REQUEST_TYPE_NAME, REQUEST_METHOD),
	
	CONSTRAINT REQUEST_TYPE_NAME_METHOD_CHECK
		CHECK(
			(REQUEST_TYPE_NAME = 'HTTP' AND REQUEST_METHOD IN('GET', 'POST', 'PUT', 'DELETE', 'PATCH')) 
			OR (REQUEST_TYPE_NAME = 'GRAPHQL' AND REQUEST_METHOD IN ('GET', 'POST')) 
			OR (REQUEST_TYPE_NAME IN ('WEBSOCKET', 'GRPC') AND REQUEST_METHOD IS NULL)
		)
);


CREATE TABLE EMAIL_TYPE(
	EMAIL_TYPE_ID SMALLINT, 
	EMAIL_TYPE_NAME VARCHAR(254), 
	EMAIL_BODY TEXT,

	CONSTRAINT EMAIL_TYPE_PK
		PRIMARY KEY (EMAIL_TYPE_ID),
	
	CONSTRAINT EMAIL_TYPE_NAME_UK	
		UNIQUE(EMAIL_TYPE_NAME), 

	CONSTRAINT EMAIL_TYPE_NAME_BODY_CHECK
		CHECK(
			EMAIL_TYPE_NAME IS NOT NULL
			AND 
			EMAIL_BODY IS NOT NULL
		)
);


CREATE TABLE NOTIFICATION_TYPE(
	NOTIFICATION_TYPE_ID SMALLINT, 
	NOTIFICATION_TYPE_NAME VARCHAR(254),

	CONSTRAINT NOTIFICATION_TYPE_PK 
		PRIMARY KEY (NOTIFICATION_TYPE_ID),

	CONSTRAINT NOTIFICATION_TYPE_NAME_UK
		UNIQUE(NOTIFICATION_TYPE_NAME),
	
	CONSTRAINT NOTIFICATION_TYPE_NAME_CHECK
		CHECK(
			NOTIFICATION_TYPE_NAME IS NOT NULL
		)
);


CREATE TABLE NOTIFICATION_STATUS(
	NOTIFICATION_STATUS_ID SMALLINT, 
	NOTIFICATION_STATUS_NAME VARCHAR(64),

	CONSTRAINT NOTIFICATION_STATUS_ID_PK 
		PRIMARY KEY(NOTIFICATION_STATUS_ID),

	CONSTRAINT NOTIFICATION_STATUS_NAME_UK 
		UNIQUE (NOTIFICATION_STATUS_NAME),
	
	CONSTRAINT NOTIFICATION_STATUS_NAME_CHECK
		CHECK(
			NOTIFICATION_STATUS_NAME IS NOT NULL
		)
);


CREATE TABLE CALL_STATUS(
	CALL_STATUS_ID SMALLINT, 
	CALL_STATUS_NAME VARCHAR(64),

	CONSTRAINT CALL_STATUS_ID_PK 
		PRIMARY KEY (CALL_STATUS_ID),

	CONSTRAINT CALL_STATUS_NAME_UK
		UNIQUE (CALL_STATUS_NAME),

	CONSTRAINT CALL_STATUS_NAME_CHECK
		CHECK(
			CALL_STATUS_NAME IS NOT NULL
		)
);


CREATE TABLE QUEUE_PROCESS_PHASE(
	QUEUE_PROCESS_PHASE_ID SMALLINT, 
	PROCESS_PHASE VARCHAR(64), 

	CONSTRAINT QUEUE_PROCESS_PHASE_PK 
		PRIMARY KEY(QUEUE_PROCESS_PHASE_ID),

	CONSTRAINT QUEUE_PROCESS_PHASE_UK
		UNIQUE(PROCESS_PHASE), 

	CONSTRAINT QUEUE_PROCESS_PHASE_CHECK
		CHECK(
			PROCESS_PHASE IS NOT NULL
		)
);

CREATE TABLE OS_TYPE(
	OS_TYPE_ID SMALLINT, 
	OS_TYPE_NAME VARCHAR(64),
	OS_VERSION VARCHAR(64),

	CONSTRAINT OS_TYPE_PK
		PRIMARY KEY(OS_TYPE_ID),

	CONSTRAINT OS_TYPE_NAME_VERSION_UK
		UNIQUE(OS_TYPE_NAME, OS_VERSION), 

	CONSTRAINT OS_TYPE_NAME_VERSION_CHECK
		CHECK(
			OS_TYPE_NAME IS NOT NULL
			AND 
			OS_VERSION IS NOT NULL
		)
);

CREATE TABLE JOB_TYPE(
	JOB_TYPE_ID SMALLINT,
	JOB_TYPE_NAME VARCHAR(64),

	CONSTRAINT JOB_TYPE_ID_PK
		PRIMARY KEY(JOB_TYPE_ID),

	CONSTRAINT JOB_TYPE_NAME_UK
		UNIQUE(JOB_TYPE_NAME), 

	CONSTRAINT JOB_TYPE_NAME_CHECK
		CHECK(
			JOB_TYPE_NAME IS NOT NULL 
		)
);

----------------MAIN TAABLES----------------

-- CLIENT
CREATE TABLE CLIENT(
	CLIENT_ID UUID DEFAULT GEN_RANDOM_UUID(), 
	CLIENT_EMAIL VARCHAR(254) NOT NULL, 
	USERNAME VARCHAR(64) NOT NULL,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100),
	VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
	CLIENT_STATUS SMALLINT NOT NULL, 
	LAST_LOGIN TIMESTAMPTZ,
	DELETED_AT TIMESTAMPTZ,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT CLIENT_PK
		PRIMARY KEY(CLIENT_ID),

	CONSTRAINT CLIENT_EMAIL_CHECK
		CHECK (CLIENT_EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
	
	CONSTRAINT CLIENT_USERNAME_CHECK
		CHECK(USERNAME ~ '^[a-zA-Z0-9_]{3,30}$'), 

	CONSTRAINT CLIENT_LAST_LOGIN_CHECK
		CHECK(LAST_LOGIN IS NULL OR LAST_LOGIN >= CREATED_AT),

	CONSTRAINT CLIENT_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT >= CREATED_AT),

	CONSTRAINT CLIENT_STATUS_FK
		FOREIGN KEY (CLIENT_STATUS)
		REFERENCES CLIENT_STATUS(CLIENT_STATUS_ID)
);

CREATE UNIQUE INDEX CLIENT_EMAIL_UNIQ_INDEX
ON CLIENT(LOWER(CLIENT_EMAIL));

CREATE UNIQUE INDEX CLIENT_USERNAME_UNIQ_INDEX
ON CLIENT(LOWER(USERNAME));

CREATE INDEX CLIENT_STATUS_INDEX 
ON CLIENT(CLIENT_STATUS);



-- PASSWORD_ALGORITHM
CREATE TABLE PASSWORD_ALGORITHM(
	PASSWORD_ALGORITHM_ID SMALLINT, 
	ALGORITHM_TYPE SMALLINT NOT NULL, 
	ALGORITHM_DESCRIPTION VARCHAR(254), 
	ITERATION INTEGER NOT NULL DEFAULT 18, -- USED ONLY FOR BCRYPT, NR OF ROUNDS
	MEMORY_COST INT NOT NULL DEFAULT 1048576,  --USED ONLY FOR ARGON2, IN KiB
	PARALLELISM INT DEFAULT 4,-- ARGON2
	SALT_LENGTH SMALLINT NOT NULL DEFAULT 256, --IN BITS 
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT PASSWORD_ALGORITHM_ID_PK 
		PRIMARY KEY(PASSWORD_ALGORITHM_ID),

	CONSTRAINT PASSWORD_ALGORITHM_TYPE_UK
		UNIQUE(ALGORITHM_TYPE),

	CONSTRAINT PASSWORD_ALGORITHM_TYPE_FK
		FOREIGN KEY (ALGORITHM_TYPE)
		REFERENCES ALGORITHM_TYPE(ALGORITHM_TYPE_ID),
	
	CONSTRAINT PASSWORD_ALGORITHM_UPDATE_CREATED_AT_CHECK
		CHECK(UPDATED_AT >= CREATED_AT) 
);


-- PASSWORD 
CREATE TABLE CLIENT_PASSWORD(
	PASSWORD_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL,
	PASSWORD_HASH TEXT NOT NULL,
	ALGORITHM_ID SMALLINT NOT NULL,
	PWD_AGE_ENABLED BOOLEAN NOT NULL DEFAULT TRUE, 
	FREQUENCY SMALLINT, --DAYS
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 

	CONSTRAINT CLIENT_PASSWORD_ID_PK
		PRIMARY KEY(PASSWORD_ID),

	CONSTRAINT CLIENT_PASSWORD_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT(CLIENT_ID),

	CONSTRAINT CLIENT_PASSWORD_ALGORITHM_ID_FK
    	FOREIGN KEY (ALGORITHM_ID)
        REFERENCES PASSWORD_ALGORITHM(PASSWORD_ALGORITHM_ID),
	
	CONSTRAINT CLIENT_PASSWORD_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT >= CREATED_AT), --
	
	CONSTRAINT CLIENT_PASSWORD_FREQUENCY_CHECK
		CHECK (FREQUENCY IS NULL OR FREQUENCY > 0)	 
);

CREATE UNIQUE INDEX CLIENT_PASSWORD_UNIQ_CLIENT_ID_INDEX
ON CLIENT_PASSWORD(CLIENT_ID);



-- PASSWORD HISTORY 
CREATE TABLE PASSWORD_HISTORY(
	PASSWORD_HISTORY_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL,
	PASSWORD_HASH TEXT NOT NULL, 
	ALGORITHM_ID SMALLINT NOT NULL,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 

	CONSTRAINT PASSWORD_HISTORY_PK
		PRIMARY KEY(PASSWORD_HISTORY_ID),

	CONSTRAINT PASSWORD_HISTORY_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID) 
		REFERENCES CLIENT(CLIENT_ID),
	
	CONSTRAINT PASSWORD_HISTORY_ALGORITHM_ID_FK
		FOREIGN KEY (ALGORITHM_ID)
		REFERENCES PASSWORD_ALGORITHM(PASSWORD_ALGORITHM_ID)
);

CREATE INDEX PASSWORD_HISTORY_CLIENT_ID_INDEX
ON PASSWORD_HISTORY(CLIENT_ID);

CREATE INDEX PASSWORD_HISTORY_CLIENT_CREATED_AT_INDEX
ON PASSWORD_HISTORY(CLIENT_ID, CREATED_AT DESC);



-- THEME 
CREATE TABLE THEME(
	THEME_ID SMALLINT, 
	COLOR_HEX VARCHAR(7) NOT NULL DEFAULT '000000',
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	COLOR_NAME VARCHAR(64) NOT NULL DEFAULT 'DARK',

	CONSTRAINT THEME_PK
		PRIMARY KEY(THEME_ID),

	CONSTRAINT THEME_COLOR_HEX_UK
		UNIQUE(COLOR_HEX),

	CONSTRAINT THEME_COLOR_NAME_UK
		UNIQUE(COLOR_NAME),

	CONSTRAINT THEME_COLOR_HEX_CHECK
		CHECK(COLOR_HEX ~ '^#[0-9a-fA-F]{6}$')
);


-- LANGUAGE
CREATE TABLE LANGUAGE(
	LANGUAGE_ID SMALLINT, 
	LANGUAGE_CODE VARCHAR(10) NOT NULL DEFAULT 'en_US',

	CONSTRAINT LANGUAGE_PK
		PRIMARY KEY(LANGUAGE_ID),

	CONSTRAINT LANGUAGE_CODE_UK 
		UNIQUE(LANGUAGE_CODE)
);


-- PREFERENCE 
CREATE TABLE PREFERENCE(
	PREFERENCE_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL,
	THEME_ID SMALLINT NOT NULL,
	LANGUAGE_ID SMALLINT NOT NULL, 
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT PREFERENCE_PK
		PRIMARY KEY(PREFERENCE_ID),

	CONSTRAINT PREFERENCE_CLIENT_ID_UK 
		UNIQUE(CLIENT_ID),

	CONSTRAINT PREFERENCE_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT(CLIENT_ID),
	
	CONSTRAINT PREFERENCE_THEME_ID_FK
		FOREIGN KEY (THEME_ID)
		REFERENCES THEME(THEME_ID),
	
	CONSTRAINT PREFERENCE_LANGUAGE_ID_FK
		FOREIGN KEY (LANGUAGE_ID)
		REFERENCES LANGUAGE(LANGUAGE_ID),
	
	CONSTRAINT PREFERENCE_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT >= CREATED_AT)
); 

CREATE INDEX PREFERENCE_CLIENT_ID_INDEX
ON PREFERENCE(CLIENT_ID);

CREATE INDEX PREFERENCE_THEME_ID_INDEX
ON PREFERENCE(THEME_ID);

CREATE INDEX PREFERENCE_LANGUAGE_ID_INDEX 
ON PREFERENCE(LANGUAGE_ID);


-- PRIVACY_SETTING
CREATE TABLE PRIVACY_SETTING(
	PRIVACY_SETTING_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL, 
	SHOW_ONLINE_STATUS BOOLEAN NOT NULL DEFAULT TRUE, 
	ALLOW_FRIEND_REQUEST BOOLEAN NOT NULL DEFAULT TRUE,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT PRIVACY_SETTING_PK 
		PRIMARY KEY(PRIVACY_SETTING_ID),

	CONSTRAINT PRIVACY_SETTING_CLIENT_ID_UK 
		UNIQUE(CLIENT_ID),

	CONSTRAINT PRIVACY_SETTING_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT >= CREATED_AT), --
	
	CONSTRAINT PRIVACY_SETTING_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT(CLIENT_ID)
);

CREATE UNIQUE INDEX PRIVACY_SETTING_CLINET_ID_UNIQ_INDEX
ON PRIVACY_SETTING(CLIENT_ID);


-- ACCOUNT_DELETION_SETTING
CREATE TABLE ACCOUNT_DELETION_SETTING(
	ACCOUNT_DELETION_SETTING_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL, 
	IS_SCHEDULED_FOR_DELETION BOOLEAN NOT NULL DEFAULT FALSE,
	DELETION_DATE TIMESTAMPTZ,
	REASON VARCHAR(254),
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT ACCOUNT_DELETION_SETTING_PK
		PRIMARY KEY(ACCOUNT_DELETION_SETTING_ID),

	CONSTRAINT ACCOUNT_DELETION_SETTING_CLIENT_ID_UK 
		UNIQUE(CLIENT_ID),

	CONSTRAINT ACCOUNT_DELETION_SETTING_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT >= CREATED_AT), --
	
	CONSTRAINT ACCOUNT_DELETION_SETTING_DELETION_DATE_CHECK
		CHECK(
			(IS_SCHEDULED_FOR_DELETION IS FALSE)
			OR 
			(IS_SCHEDULED_FOR_DELETION IS TRUE AND DELETION_DATE IS NOT NULL AND REASON IS NOT NULL AND DELETION_DATE > CURRENT_TIMESTAMP)
		),
	
	CONSTRAINT ACCOUNT_DELETION_SETTING_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT(CLIENT_ID)
); 

CREATE UNIQUE INDEX ACCOUNT_DELETION_SETTING_CLIENT_ID_UNIQ_INDEX
ON ACCOUNT_DELETION_SETTING(CLIENT_ID);



-- DATA_DELETION_SETTING
CREATE TABLE DATA_DELETION_SETTING(
	DATA_DELETION_SETTING_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL, 
	IS_SCHEDULED_FOR_DELETION BOOLEAN NOT NULL DEFAULT FALSE,
	FREQUENCY SMALLINT, 
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT DATA_DELETION_SETTING_PK
		PRIMARY KEY(DATA_DELETION_SETTING_ID),

	CONSTRAINT DATA_DELETION_SETTING_CLIENT_ID_UK 
		UNIQUE(CLIENT_ID),

	CONSTRAINT DATA_DELETION_SETTING_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT >= CREATED_AT), --
	
	CONSTRAINT DATA_DELETION_SETTING_DELETION_FREQUENCY_CHECK
		CHECK(
			(IS_SCHEDULED_FOR_DELETION IS FALSE)
			OR 
			(IS_SCHEDULED_FOR_DELETION IS TRUE AND FREQUENCY IS NOT NULL
			AND FREQUENCY >0)
		), 
	
	CONSTRAINT DATA_DELETION_SETTING_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT(CLIENT_ID)
);

CREATE UNIQUE INDEX DATA_DELETION_SETTING_CLIENT_ID_UNIQ_INDEX
ON DATA_DELETION_SETTING(CLIENT_ID);



-- BACK_UP_SETTING
CREATE TABLE BACK_UP_SETTING(
	BACK_UP_SETTING_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL,
	IS_SCHEDULED_FOR_BACK_UP BOOLEAN NOT NULL DEFAULT FALSE, 
	FREQUENCY SMALLINT, 
	STORAGE_LOCATION VARCHAR(254), 
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT BACK_UP_SETTING_PK
		PRIMARY KEY(BACK_UP_SETTING_ID),

	CONSTRAINT BACK_UP_SETTING_CLIENT_ID_UK
		UNIQUE(CLIENT_ID),

	CONSTRAINT BACK_UP_SETTING_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT >= CREATED_AT), --
	
	CONSTRAINT BACK_UP_SETTING_FEREQUENCY_CHECK
		CHECK(
			(IS_SCHEDULED_FOR_BACK_UP IS FALSE)
			OR 
			(IS_SCHEDULED_FOR_BACK_UP IS TRUE AND FREQUENCY IS NOT NULL AND STORAGE_LOCATION IS NOT NULL AND FREQUENCY >0)
		), 
	
	CONSTRAINT BACK_UP_SETTING_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT(CLIENT_ID)
);

CREATE UNIQUE INDEX BACK_UP_SETTING_CLIENT_ID_UNIQ_INDEX
ON BACK_UP_SETTING(CLIENT_ID);



-- PROFILE 
CREATE TABLE PROFILE(
	PROFILE_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL,
	PROFILE_PIC_URL TEXT,
	CAPTION TEXT,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT PROFILE_PK
		PRIMARY KEY(PROFILE_ID),

	CONSTRAINT PROFILE_CLIENT_ID_UK
		UNIQUE(CLIENT_ID),

	CONSTRAINT PROFILE_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT >= CREATED_AT), --
	
	CONSTRAINT PROFILE_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT(CLIENT_ID)
);

CREATE UNIQUE INDEX PROFILE_CLIENT_ID_UNIQ_INDEX
ON PROFILE(CLIENT_ID);



--DEVICE 
CREATE TABLE DEVICE (
	DEVICE_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL, 
	DEVICE_TYPE SMALLINT NOT NULL, 
	OS_TYPE SMALLINT NOT NULL,
	PUSH_TOKEN VARCHAR(254),
	APPLICATION_VERSION VARCHAR(64) NOT NULL,
	LAST_SEEN TIMESTAMPTZ NOT NULL,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT DEVICE_PK 
		PRIMARY KEY(DEVICE_ID),

	CONSTRAINT DEVICE_TYPE_FK
		FOREIGN KEY (DEVICE_TYPE)
		REFERENCES DEVICE_TYPE(DEVICE_TYPE_ID),
	
	CONSTRAINT DEVICE_OS_TYPE_FK
		FOREIGN KEY (OS_TYPE)
		REFERENCES OS_TYPE(OS_TYPE_ID)
); 

CREATE INDEX DEVICE_CLIENT_ID_INDEX
ON DEVICE(CLIENT_ID);



-- LOGIN_HISTORY 
CREATE TABLE LOGIN_HISTORY(
	LOGIN_HISTORY_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL, 
	REQUEST_RESULT SMALLINT NOT NULL, 
	COUNTRY VARCHAR(16) NOT NULL, --COUNTRY CODE 
	CITY VARCHAR(32) NOT NULL, 
	LONGITUDE NUMERIC(9,6), 
	LATITUDE NUMERIC(9,6),
	LOGIN_ATTEMPT_DATE TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,  
	LOGOUT_DATE TIMESTAMPTZ, 
	IP_ADDRESS INET NOT NULL, 
	OS VARCHAR(64), 
	DEVICE_ID UUID NOT NULL,

	CONSTRAINT LOGIN_HISTORY_PK
		PRIMARY KEY(LOGIN_HISTORY_ID),

	CONSTRAINT LOGIN_HISTORY_LOGOUT_DATE_CHECK
		CHECK(LOGOUT_DATE IS NULL OR LOGOUT_DATE >= LOGIN_ATTEMPT_DATE),
	
	CONSTRAINT LOGIN_HISTORY_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT(CLIENT_ID),
	
	CONSTRAINT LOGIN_HISTORY_DEVICE_ID_FK
		FOREIGN KEY (DEVICE_ID)
		REFERENCES DEVICE (DEVICE_ID),
	
	CONSTRAINT LOGIN_HISTORY_REQUEST_RESULT_FK
		FOREIGN KEY (REQUEST_RESULT)
		REFERENCES REQUEST_RESULT(REQUEST_RESULT_ID)
);

CREATE INDEX LOGIN_HISTORY_CLIENT_ID_INDEX
ON LOGIN_HISTORY(CLIENT_ID, LOGIN_ATTEMPT_DATE DESC);



-- CONTACT 
CREATE TABLE CONTACT(
	CONTACT_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CONTACTER UUID NOT NULL,
	CONTACTEE UUID NOT NULL,

	CONSTRAINT CONTACT_PK
		PRIMARY KEY(CONTACT_ID),

	CONSTRAINT CONTACT_CONTACTER_FK
		FOREIGN KEY (CONTACTER)
		REFERENCES CLIENT(CLIENT_ID),
	
	CONSTRAINT CONTACT_CONTACTEE_FK
		FOREIGN KEY (CONTACTEE)
		REFERENCES CLIENT(CLIENT_ID),
	
	CONSTRAINT CONTACT_CONTACTER_CONTACTEE_CHECK
		CHECK(CONTACTER < CONTACTEE),
	
	CONSTRAINT CONTACT_CONTACTER_CONTACTEE_UK
		UNIQUE(CONTACTER, CONTACTEE)
);

CREATE INDEX CONTACT_CONTACTER_CLIENT_ID_INDEX
ON CONTACT(CONTACTER);

CREATE INDEX CONTACT_CONTACTEE_CLIENT_ID_INDEX
ON CONTACT(CONTACTEE);



-- FRIEND_REQUEST
CREATE TABLE FRIEND_REQUEST(
	REQUEST_ID UUID DEFAULT GEN_RANDOM_UUID(),
	REQUESTER UUID,
	REQUESTEE UUID, 

	CONSTRAINT FRIEND_REQUEST_PK
		PRIMARY KEY(REQUEST_ID),

	CONSTRAINT FRIEND_REQUEST_REQUESTER_REQUESTEE_UK
		UNIQUE(REQUESTER, REQUESTEE),

	CONSTRAINT FRIEND_REQUEST_REQUESTER_FK
		FOREIGN KEY (REQUESTER) 
		REFERENCES CLIENT(CLIENT_ID),
	
	CONSTRAINT FRIEND_REQUEST_REQUESTEE_FK
		FOREIGN KEY (REQUESTEE)
		REFERENCES CLIENT(CLIENT_ID)
);



-- AUDIT_LOG
CREATE TABLE AUDIT_LOG(
	AUDIT_LOG_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL, 
	ACTION_TYPE SMALLINT NOT NULL, 
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	IP_ADDRESS INET NOT NULL, 
	ENTITY_NAME VARCHAR(254) NOT NULL, 
	REQUEST_TYPE SMALLINT NOT NULL,
	REQUEST_URL TEXT NOT NULL, 
	REQUEST_PARAM JSONB, 
	REQUEST_HEADER JSONB, 
	REQUEST_RESULT SMALLINT NOT NULL, 

	CONSTRAINT AUDIT_LOG_PK
		PRIMARY KEY(AUDIT_LOG_ID),
	
	CONSTRAINT AUDIT_LOG_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT(CLIENT_ID), 
	
	CONSTRAINT AUDIT_LOG_REQUEST_RESULT_FK
		FOREIGN KEY (REQUEST_RESULT)
		REFERENCES REQUEST_RESULT(REQUEST_RESULT_ID),
	
	CONSTRAINT AUDIT_LOG_ACTION_TYPE_FK
		FOREIGN KEY (ACTION_TYPE)
		REFERENCES ACTION_TYPE(ACTION_TYPE_ID),
	
	CONSTRAINT AUDIT_LOG_REQUEST_TYPE_FK
		FOREIGN KEY (REQUEST_TYPE)
		REFERENCES REQUEST_TYPE(REQUEST_TYPE_ID)
);

CREATE INDEX AUDIT_LOG_CLIENT_ID_INDEX
ON AUDIT_LOG(CLIENT_ID);

CREATE INDEX AUDIT_LOG_CREATED_AT_INDEX
ON AUDIT_LOG(CREATED_AT);



-- USAGE_STATISTIC
CREATE TABLE USAGE_STATISTIC(
	USAGE_STATISTIC_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL, 
	START_PERIOD TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	END_PERIOD TIMESTAMPTZ, 

	CONSTRAINT USAGE_STATISTIC_PK
		PRIMARY KEY(USAGE_STATISTIC_ID),

	CONSTRAINT USAGE_STATISTIC_END_PERIOD_CHECK
		CHECK(
			END_PERIOD IS NULL OR END_PERIOD >= START_PERIOD
		),
	
	CONSTRAINT USAGE_STATISTIC_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT(CLIENT_ID),
	
	CONSTRAINT USAGE_STATISTIC_CLIENT_ID_START_PERIOD_UK
		UNIQUE(CLIENT_ID, START_PERIOD)
);

CREATE INDEX USAGE_STATISTIC_CLIENT_ID_START_PREIOD_INDEX
ON USAGE_STATISTIC(CLIENT_ID, START_PERIOD);

CREATE INDEX USAGE_STATISTIC_CLIENT_ID_END_PREIOD_INDEX
ON USAGE_STATISTIC(CLIENT_ID, END_PERIOD);



-- EMAIL_QUEUE
CREATE TABLE EMAIL_QUEUE(
	EMAIL_QUEUE_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL, 
	EMAIL_TYPE SMALLINT NOT NULL, 
	PROCESS_PHASE SMALLINT NOT NULL, 
	ATTEMPTS SMALLINT NOT NULL DEFAULT 0,
	SCHEDULED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, 

	CONSTRAINT EMAIL_QUEUE_PK
		PRIMARY KEY(EMAIL_QUEUE_ID),

	CONSTRAINT EMAIL_QUEUE_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT IS NULL OR UPDATED_AT>=CREATED_AT),
	
	CONSTRAINT EMAIL_QUEUE_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT(CLIENT_ID),
	
	CONSTRAINT EMAIL_QUEUE_EMAIL_TYPE_FK
		FOREIGN KEY (EMAIL_TYPE)
		REFERENCES EMAIL_TYPE(EMAIL_TYPE_ID),
	
	CONSTRAINT EMAIL_QUEUE_PROCESS_PHASE_FK
		FOREIGN KEY (PROCESS_PHASE)
		REFERENCES QUEUE_PROCESS_PHASE(QUEUE_PROCESS_PHASE_ID)
);

CREATE INDEX EMAIL_QUEUE_CLIENT_ID_PROCESS_PHASE_INDEX
ON EMAIL_QUEUE(CLIENT_ID, PROCESS_PHASE);

CREATE INDEX EMAIL_QUEUE_WORKER_INDEX
ON EMAIL_QUEUE(PROCESS_PHASE, SCHEDULED_AT);



-- NOTIFICATION 
CREATE TABLE NOTIFICATION(
	NOTIFICATION_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CLIENT_ID UUID NOT NULL, 
	NOTIFICATION_TYPE SMALLINT NOT NULL, 
	CONTENT JSONB NOT NULL, 
	NOTIFICATION_STATUS SMALLINT NOT NULL,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	READ_AT TIMESTAMPTZ,

	CONSTRAINT NOTIFICATION_PK
		PRIMARY KEY(NOTIFICATION_ID),

	CONSTRAINT NOTIFICATION_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT IS NULL OR UPDATED_AT >= CREATED_AT),
	
	CONSTRAINT NOTIFICATION_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID) 
		REFERENCES CLIENT(CLIENT_ID), 
	
	CONSTRAINT NOTIFICATION_TYPE_FK
		FOREIGN KEY (NOTIFICATION_TYPE)
		REFERENCES NOTIFICATION_TYPE(NOTIFICATION_TYPE_ID),
	
	CONSTRAINT NOTIFICATION_STATUS_FK
		FOREIGN KEY (NOTIFICATION_STATUS)
		REFERENCES NOTIFICATION_STATUS(NOTIFICATION_STATUS_ID)
);


CREATE INDEX NOTIFICATION_CLIENT_ID_INDEX
ON NOTIFICATION(CLIENT_ID);

CREATE INDEX NOTIFICATION_NOTIFICATION_STATUS_CREATED_AT_INDEX
ON NOTIFICATION(NOTIFICATION_STATUS, CREATED_AT);

CREATE INDEX NOTIFICATION_UNREAD_INDEX
ON NOTIFICATION (CLIENT_ID, READ_AT) 
WHERE READ_AT IS NULL;




-- NOTIFICATION_QUEUE
CREATE TABLE NOTIFICATION_QUEUE(
	NOTIFICATION_QUEUE_ID UUID DEFAULT GEN_RANDOM_UUID(),
	NOTIFICATION_ID UUID NOT NULL, 
	PROCESS_PHASE SMALLINT NOT NULL, 
	ATTEMPTS SMALLINT NOT NULL DEFAULT 0,
	SCHEDULED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMPTZ, 

	CONSTRAINT NOTIFICATION_QUEUE_PK
		PRIMARY KEY(NOTIFICATION_QUEUE_ID),

	CONSTRAINT NOTIFICATION_ID_UK
		UNIQUE(NOTIFICATION_ID),

	CONSTRAINT NOTIFICATION_QUEUE_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT IS NULL OR UPDATED_AT>=CREATED_AT),
	
	CONSTRAINT NOTIFICATION_QUEUE_NOTIFICATION_ID_FK
		FOREIGN KEY (NOTIFICATION_ID)
		REFERENCES NOTIFICATION(NOTIFICATION_ID),
	
	CONSTRAINT NOTIFICATION_QUEUE_PROCESS_PHASE_FK
		FOREIGN KEY (PROCESS_PHASE)
		REFERENCES QUEUE_PROCESS_PHASE(QUEUE_PROCESS_PHASE_ID)	
);

CREATE INDEX NOTIFICATION_QUEUE_WORKER_INDEX
ON NOTIFICATION_QUEUE(PROCESS_PHASE, SCHEDULED_AT);



-- CONVERSATION
CREATE TABLE CONVERSATION (
    CONVERSATION_ID UUID DEFAULT GEN_RANDOM_UUID(),
    CONVERSATION_TYPE CONVERSATION_TYPE NOT NULL,
    CREATED_BY UUID NOT NULL,
	CONVERSATION_NAME TEXT,
	DELETED_AT TIMESTAMPTZ,
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT CONVERSATION_PK
		PRIMARY KEY(CONVERSATION_ID),

	CONSTRAINT CONVERSATION_CREATED_BY_FK
    	FOREIGN KEY (CREATED_BY)
        REFERENCES CLIENT(CLIENT_ID)
);



-- CONVERSATION_PARTICIPANT
CREATE TABLE CONVERSATION_PARTICIPANT (
    CONVERSATION_ID UUID,
    CLIENT_ID UUID,
    ROLE PARTICIPANT_ROLE NOT NULL,
    JOINED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LEFT_AT TIMESTAMPTZ,
    LAST_READ_AT TIMESTAMPTZ,

	CONSTRAINT CONVERSATION_PARTICIPANT_PK
    	PRIMARY KEY (CONVERSATION_ID, CLIENT_ID),
    
	CONSTRAINT CONVERSATION_PARTICIPANT_CONVERSATION_ID_FK
		FOREIGN KEY (CONVERSATION_ID)
        REFERENCES CONVERSATION(CONVERSATION_ID),
    
	CONSTRAINT CONVERSATION_PARTICIPANT_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT(CLIENT_ID),
    
	CONSTRAINT CONVERSATION_PARTICIPANT_LEFT_JOINED_AT_CHECK
		CHECK (
        	LEFT_AT IS NULL OR LEFT_AT >= JOINED_AT
    	)
);

CREATE INDEX CONVERSATION_PARTICIPANT_CLIENT_INDEX
ON CONVERSATION_PARTICIPANT(CLIENT_ID);

CREATE INDEX CONVERSATION_PARTICIPANT_LOOKUP
ON CONVERSATION_PARTICIPANT(CLIENT_ID, JOINED_AT DESC);



-- CHAT 
CREATE TABLE CHAT (
    CHAT_ID UUID DEFAULT GEN_RANDOM_UUID(),
    CONVERSATION_ID UUID NOT NULL,
    CHAT_TYPE CHAT_TYPE NOT NULL,
    SENDER UUID NOT NULL,
    CIPHER TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EDITED_AT TIMESTAMPTZ,
	DELETED_AT TIMESTAMPTZ,
    DELETED_BY_SENDER BOOLEAN NOT NULL DEFAULT FALSE,
	IS_CHAT_BLOCKED BOOLEAN NOT NULL DEFAULT FALSE,
	CHAT_SEQ BIGINT GENERATED ALWAYS AS IDENTITY,

	CONSTRAINT CHAT_PK
		PRIMARY KEY(CHAT_ID),

	CONSTRAINT CHAT_CONVERSATION_ID_FK
    	FOREIGN KEY (CONVERSATION_ID)
        REFERENCES CONVERSATION(CONVERSATION_ID),
    
	CONSTRAINT CHAT_SENDER_FK
		FOREIGN KEY (SENDER)
        REFERENCES CLIENT(CLIENT_ID),
    
	CONSTRAINT CHAT_EDITED_CREATED_AT_CHECK
		CHECK (EDITED_AT IS NULL OR EDITED_AT >= CREATED_AT),
	
	CONSTRAINT CHAT_DELETED_BY_SENDER_DELETED_AT_CHECK
		CHECK(
			DELETED_BY_SENDER IS FALSE 
			OR 
			DELETED_AT IS NOT NULL
		)
);


-- CHAT_STATUS_TRACK
CREATE TABLE CHAT_STATUS_TRACK (
    CHAT_ID UUID,
    CLIENT_ID UUID,
    DELIVERED_AT TIMESTAMPTZ,
    READ_AT TIMESTAMPTZ,

	CONSTRAINT CHAT_STATUS_TRACK_PK
    	PRIMARY KEY (CHAT_ID, CLIENT_ID),
    
	CONSTRAINT CHAT_STATUS_TRACK_CHAT_ID_FK
		FOREIGN KEY (CHAT_ID) REFERENCES CHAT(CHAT_ID),
    
	CONSTRAINT CHAT_STATUS_TRACK_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID)
);

-- CHAT_DELETION_TRACK
CREATE TABLE CHAT_DELETION_TRACK (
    CHAT_ID UUID,
    CLIENT_ID UUID,
    DELETED_AT TIMESTAMPTZ,

	CONSTRAINT CHAT_DELETION_TRACK_PK
		PRIMARY KEY(CHAT_ID, CLIENT_ID),
	
	CONSTRAINT CHAT_DELETION_TRACK_CHAT_ID_FK
		FOREIGN KEY (CHAT_ID) REFERENCES CHAT(CHAT_ID),
    
	CONSTRAINT CHAT_DELETION_TRACK_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID)
);

CREATE INDEX CHAT_CONVERSATION_CREATED_AT_INDEX
ON CHAT(CONVERSATION_ID, CREATED_AT);

CREATE INDEX CHAT_SENDER_CREATED_INDEX
ON CHAT(SENDER, CREATED_AT DESC);

CREATE UNIQUE INDEX chat_order
ON CHAT(CONVERSATION_ID, CHAT_SEQ);


-- CHAT_QUEUE
CREATE TABLE CHAT_QUEUE(
	CHAT_QUEUE_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CHAT_ID UUID NOT NULL,
	PROCESS_PHASE SMALLINT NOT NULL, 
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMPTZ, 
	ATTEMPTS SMALLINT NOT NULL DEFAULT 0,
	SCHEDULED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT CHAT_QUEUE_PK
		PRIMARY KEY(CHAT_QUEUE_ID),

	CONSTRAINT CHAT_QUEUE_CHAT_ID_UK 
		UNIQUE(CHAT_ID),

	CONSTRAINT CHAT_QUEUE_CHAT_ID_FK
		FOREIGN KEY (CHAT_ID)
		REFERENCES CHAT(CHAT_ID),
	
	CONSTRAINT CHAT_QUEUE_PROCESS_PHASE_FK
		FOREIGN KEY (PROCESS_PHASE)
		REFERENCES QUEUE_PROCESS_PHASE(QUEUE_PROCESS_PHASE_ID),
	
	CONSTRAINT CHAT_QUEUE_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT IS NULL OR UPDATED_AT>=CREATED_AT)
);

CREATE UNIQUE INDEX CHAT_QUEUE_CHAT_ID_INDEX
ON CHAT_QUEUE(CHAT_ID);

CREATE INDEX CHAT_QUEUE_WORKER_INDEX
ON CHAT_QUEUE(PROCESS_PHASE, SCHEDULED_AT);


CREATE INDEX CHAT_QUEUE_RETRY_INDEX 
ON CHAT_QUEUE(PROCESS_PHASE, ATTEMPTS);




-- CALL
CREATE TABLE CALL(
	CALL_ID UUID DEFAULT GEN_RANDOM_UUID(),
	CALL_TYPE CALL_TYPE NOT NULL,
	CREATED_BY UUID NOT NULL, 
	CALL_CONVERSATION_ID UUID NOT NULL, 
	CALL_STATUS SMALLINT NOT NULL, 
	CALL_STARTED_AT TIMESTAMPTZ, 
	CALL_ENDED_AT TIMESTAMPTZ, 
	ENCRYPTION_TYPE ENCRYPTION_TYPE NOT NULL, 
	CALL_ENDED_REASON CALL_ENDED_REASON,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, 

	CONSTRAINT CALL_PK 
		PRIMARY KEY(CALL_ID),

	CONSTRAINT CALL_UPDATED_CREATED_AT_CHECK
		CHECK(UPDATED_AT IS NULL OR UPDATED_AT>=CREATED_AT),
	
	CONSTRAINT CALL_ENDED_STARTED_AT_CHECK
		CHECK(CALL_ENDED_AT IS NULL OR CALL_STARTED_AT IS NOT NULL),
	
	CONSTRAINT CALL_ENDED_REASON_CHECK
		CHECK(CALL_ENDED_REASON IS NULL OR CALL_ENDED_AT IS NOT NULL),
	
	CONSTRAINT CALL_CREATED_BY_FK
		FOREIGN KEY (CREATED_BY) 
		REFERENCES CLIENT(CLIENT_ID),
	
	CONSTRAINT CALL_CONVERSATION_ID_FK
		FOREIGN KEY (CALL_CONVERSATION_ID)
		REFERENCES CONVERSATION(CONVERSATION_ID),
	
	CONSTRAINT CALL_STATUS_FK
		FOREIGN KEY (CALL_STATUS)
		REFERENCES CALL_STATUS(CALL_STATUS_ID)
);

CREATE INDEX CALL_CREATED_BY_STARTED_AT_ENDED_AT 
ON CALL(CREATED_BY, CALL_STARTED_AT, CALL_ENDED_AT);

CREATE INDEX CALL_CONVERSATION_ID_CREATED_INDEX
ON CALL(CALL_CONVERSATION_ID, CREATED_AT DESC);



-- CALL_PARTICIPANT
CREATE TABLE CALL_PARTICIPANT(
	CALL_ID UUID, 
	CLIENT_ID UUID, 
	JOINED_AT TIMESTAMPTZ, 
	LEFT_AT TIMESTAMPTZ, 
	PARTICIPANT_ROLE PARTICIPANT_ROLE NOT NULL, 
	WAS_MISSED BOOLEAN, 
	SUMMARY TEXT, 

	CONSTRAINT CALL_PARTICIPANT_CALL_ID_CLEINT_ID_PK
		PRIMARY KEY (CALL_ID, CLIENT_ID), 
	
	CONSTRAINT CALL_PARTICIPANT_JOINED_LEFT_AT_CHECK
		CHECK(
			(JOINED_AT IS NULL AND LEFT_AT IS NULL)
			OR 
			(JOINED_AT IS NOT NULL AND (LEFT_AT IS NULL OR LEFT_AT >= JOINED_AT))
		), 
	
	CONSTRAINT CALL_PARTICIPANT_WAS_MISSED_CHECK
		CHECK(
			WAS_MISSED IS NULL 
			OR (WAS_MISSED = TRUE AND JOINED_AT IS NULL)
			OR (WAS_MISSED = FALSE AND JOINED_AT IS NOT NULL)
		),
	
	CONSTRAINT CALL_PARTICIPANT_CALL_ID_FK
		FOREIGN KEY (CALL_ID)
		REFERENCES CALL(CALL_ID),
	
	CONSTRAINT CALL_PARTICIPANT_CLIENT_ID_FK
		FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT(CLIENT_ID)
);

CREATE INDEX CALL_PARTICIPANT_CLIENT_ID_INDEX
ON CALL_PARTICIPANT(CLIENT_ID);

CREATE UNIQUE INDEX ONE_HOST_PER_CALL
ON CALL_PARTICIPANT(CALL_ID)
WHERE PARTICIPANT_ROLE = 'HOST';


 -- BLOCKED USER
 CREATE TABLE BLOCKED_USER(
	BLOCKED_USER_ID UUID NOT NULL,
	BLOCKED_BY UUID NOT NULL,
	BLOCKED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 

	CONSTRAINT BLOCKED_USER_ID_BLOCKED_BY_PK
		PRIMARY KEY (BLOCKED_USER_ID, BLOCKED_BY),
	
	CONSTRAINT BLOCKED_USER_ID_FK
		FOREIGN KEY (BLOCKED_USER_ID)
		REFERENCES CLIENT(CLIENT_ID),
	
	CONSTRAINT BLOCKED_USER_BLOCKED_BY_FK
		FOREIGN KEY (BLOCKED_BY)
		REFERENCES CLIENT(CLIENT_ID),

	CONSTRAINT BLOCKED_USER_ID_BLOCKED_BY_CHECK
		CHECK (BLOCKED_USER_ID <> BLOCKED_BY)
 );


-- GENERIC JOB TABLE 
CREATE TABLE GENERIC_JOB(
	JOB_ID UUID,
	JOB_TYPE SMALLINT NOT NULL, 
	PAYLOAD JSONB,
	PROCESS_PHASE SMALLINT NOT NULL,
	ATTEMPTS INT NOT NULL DEFAULT 0,
	SCHEDULED_AT TIMESTAMPTZ, 
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMPTZ,

	CONSTRAINT GENERIC_JOB_PK
		PRIMARY KEY(JOB_ID),

	CONSTRAINT GENERIC_JOB_TYPE_FK
		FOREIGN KEY (JOB_TYPE)
		REFERENCES JOB_TYPE(JOB_TYPE_ID),
	
	CONSTRAINT GENERIC_JOB_PROCESS_PHASE_FK
		FOREIGN KEY (PROCESS_PHASE)
		REFERENCES QUEUE_PROCESS_PHASE(QUEUE_PROCESS_PHASE_ID)
);

CREATE INDEX GENERIC_JOB_TYPE_INDEX ON GENERIC_JOB(JOB_TYPE);