
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: secret_passwd
      timeout: 2000ms

caffeine:
  node-cache:
    max-size: 5_000
    ttl-minutes: 10
  node-cache-by-id:
    max-size: 5_000
    ttl-minutes: 10
  primary-route-cache:
    max-size: 5_000
    ttl-minutes: 10
  replica-route-cache:
    max-size: 5_000
    ttl-minutes: 10
  virtual-shard-cache:
    max-size: 5_000
    ttl-minutes: 10
  shard-index-cache:
    max-size: 5_000
    ttl-minutes: 10