----------------SHARD METADATA (HYBRID SHARDING)----------------

CREATE TYPE SHARD_STATUS AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'MIGRATING',
    'FAILED'
);

CREATE TYPE NODE_STATUS AS ENUM (
    'ONLINE',
    'OFFLINE',
    'DRAINING'
);

CREATE TYPE NODE_ROLE AS ENUM (
    'PRIMARY',
    'REPLICA'
);


CREATE TYPE MIGRATION_STATUS AS ENUM (
    'STARTED',
    'COPYING',
    'VALIDATING',
    'COMPLETED',
    'FAILED'
);

CREATE TYPE SHARD_DOMAIN AS ENUM (
    'CLIENT',
    'CHAT',
    'NOTIFICATION'
);

-- SHARD_MAP 
CREATE TABLE SHARD_MAP (
    SHARD_ID INT PRIMARY KEY,
    DATABASE_NAME VARCHAR(64) NOT NULL,
    DOMAIN SHARD_DOMAIN NOT NULL,
    STATUS SHARD_STATUS NOT NULL DEFAULT 'ACTIVE',
    VERSION BIGINT NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE SHARD_NODE(
    NODE_ID BIGSERIAL PRIMARY KEY,
    SHARD_ID INT NOT NULL
        REFERENCES SHARD_MAP(SHARD_ID),
    HOSTNAME VARCHAR(255) NOT NULL,
    PORT INT NOT NULL DEFAULT 5432,
    REGION VARCHAR(16),
    ROLE NODE_ROLE NOT NULL DEFAULT 'PRIMARY',
    NODE_STATUS NODE_STATUS NOT NULL DEFAULT 'ONLINE',
    CONNECTION_SECRET VARCHAR(128),
    MAX_CONNECTIONS INT DEFAULT 100,
    WEIGHT INT DEFAULT 100,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(SHARD_ID, HOSTNAME, PORT)
);


CREATE TABLE SHARD_MIGRATION(
    MIGRATION_ID BIGSERIAL PRIMARY KEY,
    FROM_SHARD INT NOT NULL
        REFERENCES SHARD_MAP(SHARD_ID),
    TO_SHARD INT NOT NULL
        REFERENCES SHARD_MAP(SHARD_ID),
    STATUS MIGRATION_STATUS NOT NULL DEFAULT 'STARTED',
    PROGRESS_PERCENT INT NOT NULL DEFAULT 0,
    ERROR_MESSAGE TEXT,
    STARTED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_AT TIMESTAMPTZ,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT DIFFERENT_SHARDS_CHECK
        CHECK(FROM_SHARD <> TO_SHARD)
);


CREATE TABLE SHARD_LOCK(
    SHARD_ID INT PRIMARY KEY
        REFERENCES SHARD_MAP(SHARD_ID),
    MIGRATION_ID BIGINT
        REFERENCES SHARD_MIGRATION(MIGRATION_ID),
    LOCKED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VIRTUAL_SHARD_MAP(
    DOMAIN SHARD_DOMAIN NOT NULL,
    VIRTUAL_SHARD_ID INT NOT NULL,
    SHARD_ID INT NOT NULL
        REFERENCES SHARD_MAP(SHARD_ID),
    VERSION BIGINT NOT NULL DEFAULT 1,
    PRIMARY KEY(
        DOMAIN,
        VIRTUAL_SHARD_ID
    )
);

CREATE INDEX IDX_VIRTUAL_SHARD_LOOKUP
ON VIRTUAL_SHARD_MAP(SHARD_ID);

CREATE INDEX IDX_ACTIVE_SHARDS
ON SHARD_MAP(DOMAIN, STATUS);



----------------SHARDING_FUNCTIONS----------------

CREATE OR REPLACE FUNCTION GET_VIRTUAL_SHARD(
    ENTITY_ID UUID
)
RETURNS INT
LANGUAGE SQL
AS
$$
SELECT MOD(
    (
        'X' ||
        SUBSTRING(
            REPLACE(ENTITY_ID::TEXT,'-','')
            FROM 1 FOR 8
        )
    )::BIT(32)::BIGINT,
    1024
)::INT;
$$;